FROM rust:1.78 AS builder

WORKDIR /submission

COPY . .

RUN cargo build --release
RUN cp target/release/$(ls target/release/ | grep -v '\.' | head -1) exchange

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /submission/exchange .

EXPOSE 8080

CMD ["./exchange"]