FROM gcc:13 AS builder

WORKDIR /submission

COPY . .

RUN find . -name "*.cpp" | head -1 | xargs -I {} g++ -std=c++17 -O2 -pthread -o exchange {}

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /submission/exchange .

EXPOSE 8080

CMD ["./exchange"]